// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: HUD_amoled_v1

#ifndef _HUD_AMOLED_V1_UI_H
#define _HUD_AMOLED_V1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen0.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_dist_png);    // assets/dist.png
LV_IMG_DECLARE(ui_img_lanel_png);    // assets/laneL.png
LV_IMG_DECLARE(ui_img_laner_png);    // assets/laneR.png
LV_IMG_DECLARE(ui_img_vehicle_png);    // assets/vehicle.png

// FONTS
LV_FONT_DECLARE(ui_font_MontserratBold32);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
