// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: HUD_amoled_v1

#include "ui.h"
#include "hudCtrl.h"



void ui_btnSetting_event_handler(lv_event_t * e)
{
	lv_obj_clear_flag(ui_contSetting, LV_OBJ_FLAG_HIDDEN);
    start_calibration();	
}

void ui_contSetting_event_handler(lv_event_t * e)
{
	lv_obj_add_flag(ui_contSetting, LV_OBJ_FLAG_HIDDEN);
    stop_calibration();
}

void ui_btnSetL_event_handler(lv_event_t * e)
{
    set_lane_left();
}

void ui_btnSetR_event_handler(lv_event_t * e)
{
    set_lane_right();
}

void ui_btnSave_event_handler(lv_event_t * e)
{
    save_calibration();
}
