// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: HUD_amoled_v1

#ifndef UI_SCREEN0_H
#define UI_SCREEN0_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen0
extern void ui_Screen0_screen_init(void);
extern void ui_Screen0_screen_destroy(void);
extern lv_obj_t * ui_Screen0;
extern lv_obj_t * ui_dist;
extern lv_obj_t * ui_laneL;
extern lv_obj_t * ui_laneR;
extern lv_obj_t * ui_vehicle;
extern void ui_event_btnSetting(lv_event_t * e);
extern lv_obj_t * ui_btnSetting;
extern void ui_event_contSetting(lv_event_t * e);
extern lv_obj_t * ui_contSetting;
extern void ui_event_btnSetL(lv_event_t * e);
extern lv_obj_t * ui_btnSetL;
extern void ui_event_btnSetR(lv_event_t * e);
extern lv_obj_t * ui_btnSetR;
extern void ui_event_btnSave(lv_event_t * e);
extern lv_obj_t * ui_btnSave;
extern lv_obj_t * ui_LabelCurL;
extern lv_obj_t * ui_LabelCurR;
extern lv_obj_t * ui_LabelOffset;
extern lv_obj_t * ui_LabelSetL;
extern lv_obj_t * ui_LabelSetR;
extern lv_obj_t * ui_textSetBtnL;
extern lv_obj_t * ui_textSetBtnR;
extern lv_obj_t * ui_textSetBtnR1;
extern lv_obj_t * ui_textCurL;
extern lv_obj_t * ui_textCurR;
extern lv_obj_t * ui_textoffset;
extern lv_obj_t * ui_textSetL;
extern lv_obj_t * ui_textSetR;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

