// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: HUD_amoled_v1

#include "ui.h"

lv_obj_t * ui_Screen0 = NULL;
lv_obj_t * ui_dist = NULL;
lv_obj_t * ui_laneL = NULL;
lv_obj_t * ui_laneR = NULL;
lv_obj_t * ui_vehicle = NULL;
lv_obj_t * ui_btnSetting = NULL;
lv_obj_t * ui_contSetting = NULL;
lv_obj_t * ui_btnSetL = NULL;
lv_obj_t * ui_btnSetR = NULL;
lv_obj_t * ui_btnSave = NULL;
lv_obj_t * ui_LabelCurL = NULL;
lv_obj_t * ui_LabelCurR = NULL;
lv_obj_t * ui_LabelOffset = NULL;
lv_obj_t * ui_LabelSetL = NULL;
lv_obj_t * ui_LabelSetR = NULL;
lv_obj_t * ui_textSetBtnL = NULL;
lv_obj_t * ui_textSetBtnR = NULL;
lv_obj_t * ui_textSetBtnR1 = NULL;
lv_obj_t * ui_textCurL = NULL;
lv_obj_t * ui_textCurR = NULL;
lv_obj_t * ui_textoffset = NULL;
lv_obj_t * ui_textSetL = NULL;
lv_obj_t * ui_textSetR = NULL;
// event funtions
void ui_event_btnSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_btnSetting_event_handler(e);
    }
}

void ui_event_contSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_contSetting_event_handler(e);
    }
}

void ui_event_btnSetL(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_btnSetL_event_handler(e);
    }
}

void ui_event_btnSetR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_btnSetR_event_handler(e);
    }
}

void ui_event_btnSave(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_btnSave_event_handler(e);
    }
}

// build funtions

void ui_Screen0_screen_init(void)
{
    ui_Screen0 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dist = lv_img_create(ui_Screen0);
    lv_img_set_src(ui_dist, &ui_img_dist_png);
    lv_obj_set_width(ui_dist, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dist, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dist, 0);
    lv_obj_set_y(ui_dist, -100);
    lv_obj_set_align(ui_dist, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dist, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dist, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_laneL = lv_img_create(ui_Screen0);
    lv_img_set_src(ui_laneL, &ui_img_lanel_png);
    lv_obj_set_width(ui_laneL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_laneL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_laneL, -200);
    lv_obj_set_y(ui_laneL, 50);
    lv_obj_set_align(ui_laneL, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_laneL, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_laneL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_laneR = lv_img_create(ui_Screen0);
    lv_img_set_src(ui_laneR, &ui_img_laner_png);
    lv_obj_set_width(ui_laneR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_laneR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_laneR, 200);
    lv_obj_set_y(ui_laneR, 50);
    lv_obj_set_align(ui_laneR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_laneR, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_laneR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_vehicle = lv_img_create(ui_Screen0);
    lv_img_set_src(ui_vehicle, &ui_img_vehicle_png);
    lv_obj_set_width(ui_vehicle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vehicle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vehicle, 0);
    lv_obj_set_y(ui_vehicle, 90);
    lv_obj_set_align(ui_vehicle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_vehicle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_vehicle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnSetting = lv_btn_create(ui_Screen0);
    lv_obj_set_width(ui_btnSetting, 100);
    lv_obj_set_height(ui_btnSetting, 70);
    lv_obj_set_x(ui_btnSetting, 245);
    lv_obj_set_y(ui_btnSetting, -190);
    lv_obj_set_align(ui_btnSetting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSetting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnSetting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contSetting = lv_obj_create(ui_Screen0);
    lv_obj_remove_style_all(ui_contSetting);
    lv_obj_set_width(ui_contSetting, 600);
    lv_obj_set_height(ui_contSetting, 450);
    lv_obj_set_align(ui_contSetting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contSetting, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_contSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contSetting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contSetting, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSetL = lv_btn_create(ui_contSetting);
    lv_obj_set_width(ui_btnSetL, 120);
    lv_obj_set_height(ui_btnSetL, 70);
    lv_obj_set_x(ui_btnSetL, 185);
    lv_obj_set_y(ui_btnSetL, -10);
    lv_obj_set_align(ui_btnSetL, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSetL, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSetL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnSetL, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSetL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSetR = lv_btn_create(ui_contSetting);
    lv_obj_set_width(ui_btnSetR, 120);
    lv_obj_set_height(ui_btnSetR, 70);
    lv_obj_set_x(ui_btnSetR, 185);
    lv_obj_set_y(ui_btnSetR, 70);
    lv_obj_set_align(ui_btnSetR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSetR, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSetR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnSetR, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSetR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSave = lv_btn_create(ui_contSetting);
    lv_obj_set_width(ui_btnSave, 150);
    lv_obj_set_height(ui_btnSave, 70);
    lv_obj_set_x(ui_btnSave, 0);
    lv_obj_set_y(ui_btnSave, 150);
    lv_obj_set_align(ui_btnSave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnSave, lv_color_hex(0x3E54FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCurL = lv_label_create(ui_contSetting);
    lv_obj_set_width(ui_LabelCurL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCurL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCurL, -390);
    lv_obj_set_y(ui_LabelCurL, -170);
    lv_obj_set_align(ui_LabelCurL, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelCurL, "");
    lv_obj_set_style_text_align(ui_LabelCurL, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCurL, &ui_font_MontserratBold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCurR = lv_label_create(ui_contSetting);
    lv_obj_set_width(ui_LabelCurR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCurR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCurR, -60);
    lv_obj_set_y(ui_LabelCurR, -170);
    lv_obj_set_align(ui_LabelCurR, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelCurR, "");
    lv_obj_set_style_text_align(ui_LabelCurR, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCurR, &ui_font_MontserratBold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOffset = lv_label_create(ui_contSetting);
    lv_obj_set_width(ui_LabelOffset, 80);
    lv_obj_set_height(ui_LabelOffset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOffset, -240);
    lv_obj_set_y(ui_LabelOffset, -100);
    lv_obj_set_align(ui_LabelOffset, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelOffset, "");
    lv_obj_set_style_text_align(ui_LabelOffset, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOffset, &ui_font_MontserratBold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSetL = lv_label_create(ui_contSetting);
    lv_obj_set_width(ui_LabelSetL, 80);
    lv_obj_set_height(ui_LabelSetL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSetL, -240);
    lv_obj_set_y(ui_LabelSetL, -10);
    lv_obj_set_align(ui_LabelSetL, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelSetL, "");
    lv_obj_set_style_text_align(ui_LabelSetL, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSetL, &ui_font_MontserratBold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSetR = lv_label_create(ui_contSetting);
    lv_obj_set_width(ui_LabelSetR, 80);
    lv_obj_set_height(ui_LabelSetR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSetR, -240);
    lv_obj_set_y(ui_LabelSetR, 70);
    lv_obj_set_align(ui_LabelSetR, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelSetR, "");
    lv_obj_set_style_text_align(ui_LabelSetR, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSetR, &ui_font_MontserratBold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textSetBtnL = lv_label_create(ui_contSetting);
    lv_obj_set_width(ui_textSetBtnL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textSetBtnL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textSetBtnL, 185);
    lv_obj_set_y(ui_textSetBtnL, -10);
    lv_obj_set_align(ui_textSetBtnL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textSetBtnL, "SET");
    lv_obj_set_style_text_align(ui_textSetBtnL, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textSetBtnL, &ui_font_MontserratBold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textSetBtnR = lv_label_create(ui_contSetting);
    lv_obj_set_width(ui_textSetBtnR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textSetBtnR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textSetBtnR, 185);
    lv_obj_set_y(ui_textSetBtnR, 70);
    lv_obj_set_align(ui_textSetBtnR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textSetBtnR, "SET");
    lv_obj_set_style_text_align(ui_textSetBtnR, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textSetBtnR, &ui_font_MontserratBold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textSetBtnR1 = lv_label_create(ui_contSetting);
    lv_obj_set_width(ui_textSetBtnR1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textSetBtnR1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textSetBtnR1, 0);
    lv_obj_set_y(ui_textSetBtnR1, 150);
    lv_obj_set_align(ui_textSetBtnR1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textSetBtnR1, "SAVE");
    lv_obj_set_style_text_align(ui_textSetBtnR1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textSetBtnR1, &ui_font_MontserratBold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textCurL = lv_label_create(ui_contSetting);
    lv_obj_set_width(ui_textCurL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textCurL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textCurL, 50);
    lv_obj_set_y(ui_textCurL, -170);
    lv_obj_set_align(ui_textCurL, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_textCurL, "Left :");
    lv_obj_set_style_text_align(ui_textCurL, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textCurL, &ui_font_MontserratBold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textCurR = lv_label_create(ui_contSetting);
    lv_obj_set_width(ui_textCurR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textCurR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textCurR, 350);
    lv_obj_set_y(ui_textCurR, -170);
    lv_obj_set_align(ui_textCurR, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_textCurR, "Right :");
    lv_obj_set_style_text_align(ui_textCurR, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textCurR, &ui_font_MontserratBold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textoffset = lv_label_create(ui_contSetting);
    lv_obj_set_width(ui_textoffset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textoffset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textoffset, 103);
    lv_obj_set_y(ui_textoffset, -100);
    lv_obj_set_align(ui_textoffset, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_textoffset, "Offset :");
    lv_obj_set_style_text_font(ui_textoffset, &ui_font_MontserratBold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textSetL = lv_label_create(ui_contSetting);
    lv_obj_set_width(ui_textSetL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textSetL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textSetL, 100);
    lv_obj_set_y(ui_textSetL, -10);
    lv_obj_set_align(ui_textSetL, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_textSetL, "Set left :");
    lv_obj_set_style_text_font(ui_textSetL, &ui_font_MontserratBold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textSetR = lv_label_create(ui_contSetting);
    lv_obj_set_width(ui_textSetR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textSetR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textSetR, 100);
    lv_obj_set_y(ui_textSetR, 70);
    lv_obj_set_align(ui_textSetR, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_textSetR, "Set right :");
    lv_obj_set_style_text_font(ui_textSetR, &ui_font_MontserratBold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnSetting, ui_event_btnSetting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSetL, ui_event_btnSetL, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSetR, ui_event_btnSetR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSave, ui_event_btnSave, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_contSetting, ui_event_contSetting, LV_EVENT_ALL, NULL);

}

void ui_Screen0_screen_destroy(void)
{
    if(ui_Screen0) lv_obj_del(ui_Screen0);

    // NULL screen variables
    ui_Screen0 = NULL;
    ui_dist = NULL;
    ui_laneL = NULL;
    ui_laneR = NULL;
    ui_vehicle = NULL;
    ui_btnSetting = NULL;
    ui_contSetting = NULL;
    ui_btnSetL = NULL;
    ui_btnSetR = NULL;
    ui_btnSave = NULL;
    ui_LabelCurL = NULL;
    ui_LabelCurR = NULL;
    ui_LabelOffset = NULL;
    ui_LabelSetL = NULL;
    ui_LabelSetR = NULL;
    ui_textSetBtnL = NULL;
    ui_textSetBtnR = NULL;
    ui_textSetBtnR1 = NULL;
    ui_textCurL = NULL;
    ui_textCurR = NULL;
    ui_textoffset = NULL;
    ui_textSetL = NULL;
    ui_textSetR = NULL;

}
